# Generated by Django 2.1.7 on 2019-03-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('email', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('age', models.CharField(max_length=30)),
            ],
        ),
    ]
